import { z } from "zod";

export const agentQuestionVariantSchema = z.enum(["markdown", "choices", "cards"]);
export const agentQuestionSelectionModeSchema = z.enum(["single", "multiple"]);

export const agentQuestionOptionSchema = z.object({
  id: z.string().trim().min(1).max(80),
  title: z.string().trim().min(1).max(80),
  description: z.string().trim().max(240).optional(),
  detail: z.string().trim().max(500).optional(),
  value: z.string().trim().min(1).max(500).optional(),
  badge: z.string().trim().max(24).optional(),
});

export const agentQuestionResolvedSchema = z.object({
  optionIds: z.array(z.string()).max(8),
  value: z.string().trim().max(1_000),
  label: z.string().trim().max(240).optional(),
  resolvedAt: z.string().optional(),
});

const agentQuestionOptionListSchema = z.array(agentQuestionOptionSchema).max(8);

const agentQuestionModelCommonShape = {
  selectionMode: agentQuestionSelectionModeSchema.default("single").describe("选择模式"),
  allowFreeText: z.boolean().optional().describe("是否允许用户补充自由文本"),
  submitLabel: z.string().trim().max(24).optional().describe("提交按钮文案"),
  placeholder: z.string().trim().max(120).optional().describe("自由文本输入框占位文案"),
};

/**
 * Model-facing AskUser UI configuration.
 *
 * Keep this separate from AgentQuestion: `resolved` is application-owned state
 * and must never be generated by the model. The discriminated union also makes
 * the choices/cards options requirement visible in provider JSON Schema.
 */
export const agentQuestionInputSchema = z.discriminatedUnion("variant", [
  z.object({
    variant: z.literal("markdown").describe("自由文本回答界面"),
    ...agentQuestionModelCommonShape,
  }),
  z.object({
    variant: z.literal("choices").describe("紧凑选项列表"),
    ...agentQuestionModelCommonShape,
    options: agentQuestionOptionListSchema.min(1).describe("至少一个可选项"),
  }),
  z.object({
    variant: z.literal("cards").describe("卡片式选项列表"),
    ...agentQuestionModelCommonShape,
    options: agentQuestionOptionListSchema.min(1).describe("至少一个可选项"),
  }),
]);

export const agentQuestionSchema = z.object({
  variant: agentQuestionVariantSchema.default("markdown"),
  selectionMode: agentQuestionSelectionModeSchema.default("single"),
  options: agentQuestionOptionListSchema.optional(),
  allowFreeText: z.boolean().optional(),
  submitLabel: z.string().trim().max(24).optional(),
  placeholder: z.string().trim().max(120).optional(),
  resolved: agentQuestionResolvedSchema.optional(),
}).superRefine((question, ctx) => {
  if (question.variant === "markdown") return;
  if (!question.options || question.options.length === 0) {
    ctx.addIssue({
      code: "custom",
      path: ["options"],
      message: "choices/cards questions must include at least one option.",
    });
  }
});

export type AgentQuestionVariant = z.infer<typeof agentQuestionVariantSchema>;
export type AgentQuestionSelectionMode = z.infer<typeof agentQuestionSelectionModeSchema>;
export type AgentQuestionOption = z.infer<typeof agentQuestionOptionSchema>;
export type AgentQuestionResolved = z.infer<typeof agentQuestionResolvedSchema>;
export type AgentQuestionInput = z.infer<typeof agentQuestionInputSchema>;
export type AgentQuestion = z.infer<typeof agentQuestionSchema>;
